print("### REQUEST TACTICAL DOLL ###")
irfan  = input("Masukkan nama Tactical Doll :")
irfan1 = input("Masukkan nama Firepower :")
irfan2 = input("Masukkan Rate of Fire :")
irfan3 = input("Masukkan Accuracy :")
irfan4 = input("Masukkan Evasion ")
demage_per_second = round (float(irfan1) * float(irfan2)/60,2)
combat_effectiveness = int(30 * float(irfan) + (40 * (float(irfan2) ** 2)/120) + (15 * (float(irfan3) + float(irfan4))))

print("### SUCCESS ###")
print("Tactical Doll:" + str(irfan))
print("Firepower:" + str(irfan1))
print ("Rate of Fire : " +str(irfan2))
print("Accurancy:" + str(irfan3)) 
print("Evasion: " + str(irfan4))
print("Damage per second: " +str(demage_per_second))
print("combat Effectiveness: " + str(combat_effectiveness))