print("### REQUEST TACTICAL DOLL ###")
name = input("Masukan nama Tactical Doll :")
nameI = input("Masukan firepower :")
nameJ = input("masukan Rate of Fire :")
nameK = input("Masukan Accuracy :")
nameL = input("masukan Evasion :")
damage_per_second = round (float(nameI) * float(nameJ)/60,2)
combat_effectiveness = int(30 * float (nameI) + (40 * (float(nameJ) ** 2)/120) + (15 * (float(nameK)+ float(nameL))))
                           
print("### SUCCESS ####")
print("Tactical Doll : " + str(name))
print("firepower : " + str(nameI))
print("Rate of Fire :"+ str(nameJ))
print("Accurancy :" +str(nameK))
print("Evasion:" +str(nameL))
print("Damage_per_second : "+str(damage_per_second)) 
print("combat Effectiveness :" + str(combat_effectiveness))