print("### REQUEST TACTICAL DOLL ###")
egi  = input("Masukkan nama Tactical Doll :")
egi1 = input("Masukkan nama Firepower :")
egi2 = input("Masukkan Rate of Fire :")
egi3 = input("Masukkan Accuracy :")
egi4 = input("Masukkan Evasion ")
demage_per_second = round (float(egi1) * float(egi2)/60,2)
combat_effectiveness = int(30 * float(egi) + (40 * (float(egi2) ** 2)/120) + (15 * (float(egi3) + float(egi4))))

print("### SUCCESS ###")
print("Tactical Doll:" + str(egi))
print("Firepower:" + str(egi1))
print ("Rate of Fire : " +str(egi2))
print("Accurancy:" + str(egi3)) 
print("Evasion: " + str(egi4))
print("Damage per second: " +str(demage_per_second))
print("combat Effectiveness: " + str(combat_effectiveness))