print("### REQUEST TACTICAL DOLL ###")
name = input("Masukan nama Tactical Doll :")
nameA = input("Masukan firepower :")
nameB = input("masukan Rate of Fire :")
nameC = input("Masukan Accuracy :")
nameD = input("masukan Evasion :")
damage_per_second = round (float(nameA) * float(nameB)/60,2)
combat_effectiveness = int(30 * float (nameA) + (40 * (float(nameB) ** 2)/120) + (15 * (float(nameC)+ float(nameD))))
                           
print("### SUCCESS ####")
print("Tactical Doll : " + str(name))
print("firepower : " + str(nameA))
print("Rate of Fire :"+ str(nameB))
print("Accurancy :" +str(nameC))
print("Evasion:" +str(nameD))
print("Damage_per_second : "+str(damage_per_second)) 
print("combat Effectiveness :" + str(combat_effectiveness))