print("### REQUEST TACTICAL DOLL ###")
tactical_doll = input("Masukan nama Tactical Doll :")
firepower = input("Masukan Firepower :")
rate_of_fire = input("Masukan Rate of Fire :")
accuracy = input("Masukan Accuracy :")
evasion = input("Masukan Evasion")
damage_per_second = round (float(firepower) * float(rate_of_fire)/60,2)
combat_effectiveness = int(30 * float(Firepower) + (40 * (float(rate_of_fire) ** 2)/120) + (15 * (float(accuracy) + float(evasion))))

print("### SUCCESS ###")
print("Tactical Doll : " + str(tactical_doll))
print("Firepower : " + str(firepower))
print("Rate of Fire : " + str(rate_of_fire))
print("Accurancy : " + str(accuracy))
print("Evasion : " + str(evasion))
print("Damage per second : " + str(damage_per_second))
print("Combat Effectiveness : " + str(combat_effectiveness))
