print("### REQUEST TACTICAL DOLL ###")
nama = input("Masukan nama Tactical Doll :")
namaI = input("Masukan firepower :")
namaJ = input("masukan Rate of Fire :")
namaK = input("Masukan Accuracy :")
namaL = input("masukan Evasion :")
damage_per_second = round (float(namaI) * float(namaJ)/60,2)
combat_effectiveness = int(30 * float (namaI) + (40 * (float(namaJ) ** 2)/120) + (15 * (float(namaK)+ float(namaL))))
                           
print("### SUCCESS ####")
print("Tactical Doll : " + str(nama))
print("firepower : " + str(namaI))
print("Rate of Fire :"+ str(namaJ))
print("Accurancy :" +str(namaK))
print("Evasion:" +str(namaL))
print("Damage_per_second : "+str(damage_per_second)) 
print("combat Effectiveness :" + str(combat_effectiveness))