print("### REQUEST TACTICAL DOLL ###")
azhari  = input("Masukkan nama Tactical Doll :")
azhari1 = input("Masukkan nama Firepower :")
azhari2 = input("Masukkan Rate of Fire :")
azhari3 = input("Masukkan Accuracy :")
azhari4 = input("Masukkan Evasion ")
demage_per_second = round (float(azhari1) * float(azhari2)/60,2)
combat_effectiveness = int(30 * float(azhari) + (40 * (float(azhari2) ** 2)/120) + (15 * (float(azhari3) + float(azhari4))))

print("### SUCCESS ###")
print("Tactical Doll:" + str(azhari))
print("Firepower:" + str(azhari1))
print ("Rate of Fire : " +str(azhari2))
print("Accurancy:" + str(azhari3)) 
print("Evasion: " + str(azhari4))
print("Damage per second: " +str(demage_per_second))
print("combat Effectiveness: " + str(combat_effectiveness))