print("### REQUES TACTICAL DOLL")
arlian =input("masukkan arlian tactical doll :")
arlian1 =input("masukan firepower :")
arlian2 =input("masukan rate of fire:")
arlian3 =input("masukan acuracy:")
arlian4 =input("masukan evasion")
damage_per_second= round(float(arlian1) * float(arlian2)/60,2)
combat_effectiveness= int(30 * float(arlian1)+(40*(float(arlian2)**2)/120) + (15*(float(arlian3) + float(arlian4))))

print("### SUCCES ###")
print("tactical doll : " + str(arlian))
print("fire power : " + str(arlian1))
print("rate of fire : " + str(arlian2))
print("accuracy :" + str(arlian3))
print("evasion :" + str(arlian4))
print("damage per second : " + str(damage_per_second))
print("combat effectivensss : " + str(combat_effectiveness))