print("### REQUEST TACTICAL DOLL ###")
nama = input("Masukan nama Tactical Doll :")
nama1 = input("Masukan Firepower :")
nama2 = input("Masukan Rate of Fire :")
nama3 = input("Masukan Accuracy :")
nama4 = input("Masukan Evasion")
damage_per_second = round (float(nama1) * float(nama2)/60,2)
combat_effectiveness = int(30 * float(nama1) + (40 * (float(nama2) ** 2)/120) + (15 * (float(nama3) + float(nama4))))

print("### SUCCESS ###")
print("Tactical Doll : " + str(nama))
print("Firepower : " + str(nama1))
print("Rate of Fire : " + str(nama2))
print("Accurancy : " + str(nama3))
print("Evasion : " + str(nama4))
print("Damage per second : " +str(damage_per_second))
print("combat Effectiveness : " + str(combat_effectiveness))
